@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

UniqueAppointmentList -down-> "*" Appointment
Appointment *--> "1" DateTime
Appointment *--> "1" Nric
Appointment *--> "1" Name
@enduml
