@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant "User" as User LOGIC_COLOR
participant ":RecordCard" as RecordCard LOGIC_COLOR
participant ":FileChooser" as FileChooser LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Record" as Record MODEL_COLOR
end box

box UI UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
end box


User -> RecordCard : User Interaction
activate RecordCard

RecordCard -> FileChooser : handleAttachFile()
activate FileChooser

FileChooser -> User : File Selection
deactivate FileChooser

User -> RecordCard : File Chosen
activate RecordCard

RecordCard -> Record : setFilePath()
activate Record

Record --> RecordCard : Path Set
deactivate Record

RecordCard -> MainWindow : Update Display
activate MainWindow
deactivate RecordCard

MainWindow --> RecordCard : Display Updated
deactivate MainWindow

@enduml
