@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":DeleteAppointmentCommandParser" as DeleteAppointmentCommandParser LOGIC_COLOR
participant "c:DeleteAppointmentCommand" as DeleteAppointmentCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("deleteappointment 1")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("deleteappointment 1")
activate AddressBookParser

create DeleteAppointmentCommandParser
AddressBookParser -> DeleteAppointmentCommandParser
activate DeleteAppointmentCommandParser

DeleteAppointmentCommandParser --> AddressBookParser
deactivate DeleteAppointmentCommandParser

AddressBookParser -> DeleteAppointmentCommandParser : parse("1")
activate DeleteAppointmentCommandParser

create DeleteAppointmentCommand
DeleteAppointmentCommandParser -> DeleteAppointmentCommand
activate DeleteAppointmentCommand

DeleteAppointmentCommand --> DeleteAppointmentCommandParser : c
deactivate DeleteAppointmentCommand

DeleteAppointmentCommandParser --> AddressBookParser : c
deactivate DeleteAppointmentCommand
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteAppointmentCommandParser -[hidden]-> AddressBookParser
destroy DeleteAppointmentCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> DeleteAppointmentCommand : execute(model)
activate DeleteAppointmentCommand

DeleteAppointmentCommand -> Model : setPerson(targetPerson, newPerson)
activate Model

Model --> DeleteAppointmentCommand
deactivate Model

DeleteAppointmentCommand -> Model : resetAppointmentList()
activate Model

Model --> DeleteAppointmentCommand
deactivate Model

create CommandResult
DeleteAppointmentCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteAppointmentCommand
deactivate CommandResult

DeleteAppointmentCommand --> LogicManager : result
deactivate DeleteAppointmentCommand


[<--LogicManager
deactivate LogicManager
@enduml
