@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FindRecordCommandParser" as FindRecordCommandParser LOGIC_COLOR
participant "c:FindRecordCommand" as FindRecordCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box


box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "predicate:RecordContainsKeywordsPredicate" as Predicate MODEL_COLOR
end box



[-> LogicManager : "searchrecord Fever"
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("searchrecord Fever")
activate AddressBookParser

create FindRecordCommandParser
AddressBookParser -> FindRecordCommandParser
activate FindRecordCommandParser

FindRecordCommandParser --> AddressBookParser
deactivate FindRecordCommandParser

AddressBookParser -> FindRecordCommandParser : parse("Fever")
activate FindRecordCommandParser

create FindRecordCommand
FindRecordCommandParser -> FindRecordCommand
activate FindRecordCommand

FindRecordCommand --> FindRecordCommandParser : c
deactivate FindRecordCommand

FindRecordCommandParser --> AddressBookParser : c
deactivate FindRecordCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
FindRecordCommandParser -[hidden]-> AddressBookParser
deactivate FindRecordCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> FindRecordCommand : execute(model)
activate FindRecordCommand

FindRecordCommand -> Model : updateFilteredRecordList(predicate)
activate Model

loop for each record in List
    Model -> Predicate : test(record)
    activate Predicate
    Predicate --> Model : result
    deactivate Predicate
end

Model --> FindRecordCommand : filteredList
deactivate Model

create CommandResult
FindRecordCommand -> CommandResult
activate CommandResult

CommandResult --> FindRecordCommand
deactivate CommandResult

FindRecordCommand --> LogicManager : result
deactivate FindRecordCommand

@enduml
