@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class UniqueRecordList
Class UniqueAppointmentList
Class Person
Class Email
Class Name
Class Phone
Class Age
Class Allergy
Class Gender
Class Phone
Class Nric
Class Record
Class DateTime
Class Condition
Class Medication
Class Appointment

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ReadOnlyUserPrefs -[hidden]right- Model

AddressBook .up.|> ReadOnlyAddressBook
ModelManager .up.|> Model
UserPrefs .up.|> ReadOnlyUserPrefs
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -down-> "1" AddressBook
ModelManager -down-> "1" UserPrefs

AddressBook *--> "2" UniquePersonList
AddressBook *--> "1" UniqueRecordList
AddressBook *--> "1" UniqueAppointmentList
UniquePersonList --> "~* all" Person
UniqueRecordList --> "~* all" Record
UniqueAppointmentList --> "~* all" Appointment
Person *--> Name
Person *--> Phone
Person *--> Email
Person *--> Age
Person *--> Gender
Person *--> "*" Allergy
Person *-right-> "*" Record
Person *--> Nric
Record *--> DateTime
Record *--> "*" Condition
Record *--> "*" Medication
Appointment *--> DateTime
Appointment *--> Name
Appointment *--> Nric

ModelManager -[hidden]down- UniquePersonList
ModelManager -[hidden]down- UniqueRecordList
ModelManager -[hidden]down- UniqueAppointmentList

ModelManager --> "~* filtered" Person
ModelManager --> "~* filtered" Record
ModelManager --> "~* filtered" Appointment

@enduml
